### ISSUE TITLE
It's not working with a few movies

### ISSUE THREAD

**Issue by felipemeamaral** [gergooo/MoviesAndVegetables#43]
Example: https://www.imdb.com/title/tt0254455/?ref_=hm_tpks_tt_4_pd_tp1
It doesn't work with this release in particupar, and it does exist in RT database.
Which is kinda oddd.
ANd thanks for such nice work, I'm love using it, it has the same feel and design from IMDB, it seems like it's been part of the site.

**Comment by gergooo** [comment]
Hi there, thank you very much for the bug ticket, and also for the nice words, I'm glad you love the extension. : )

The problem exists because Movies&Vegetables uses the original title (Lucía y el sexo) from IMDb, which is always there, but unfortunately RottenTomatoes is not that consistent: some movies are represented by their English title only, like in this case.

I will try to fix this as soon as I can.

**Comment by felipemeamaral** [comment]
Thank you for your support, @gergooo!
I'm using it every single day and am always astonished by how pretty and consistent this thing is, it's very appreciated.
And I'l wait patiently for your bugfix.
Unfortunately I'm not a web developer, if I was I'll be very glad to help you with the project.
Cheers from Brazil and I hope that this new year will be much better for ourselves and for our families as well.

**Comment by gergooo** [comment]
No problem, thank you for the kind words, Felipe! : )

There is a new version, hopefully your browser will receive it soon (or you can update manually in the Addons menu). It improves the movie search algorithm and fixes this particular case.

Originally, I had a more complex solution in mind, but it looks like a small improvement was enough. If you find it otherwise and/or bump into another cases, please don't hesitate to tell me, I appreciate it a lot!

Cheers from Hungary. :-)
